services:
  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  migrate:
    image: payment_processor:latest
    env_file:
      - .env
    environment:
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__HOST: db
      DB__PORT: ${DB__PORT}
      DB__NAME: ${DB__NAME}
    command: [ "/app/.venv/bin/alembic", "upgrade", "head" ]
    depends_on:
      db:
        condition: service_healthy

  payment_processor:
    build:
      context: .
      target: production-image
    image: payment_processor:latest
    env_file:
      - .env
    environment:
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__HOST: db
      DB__PORT: ${DB__PORT}
      DB__NAME: ${DB__NAME}
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  db_vol:
